### PR TITLE
Add support for operation compression for most data types

### PR DESCRIPTION
**Pull request by gmcabrita**
This pull request adds support for operation compression for most of the data types defined in antidote_crdt and adds some unit tests to verify that the compression functions are working as expected.

The data types without currently defined compression functions will continue to function as usual (even with compression enabled in Antidote) but won't be able to be compressed. Those data types can always be extended in the future to support this.

**This pull request should be merged before merging SyncFree/antidote#296**

### CODE REVIEW

**Comment by bieniusa** [comment]
Looks good for me at quick glance.

@gmcabrita Can you open an issue with a list of the crdts that have a todo for the compression?
Otherwise, we will forget about it.

**Comment by gmcabrita** [comment]
I've opened the issue: #19

**Comment by peterzeller** [comment]
I tried to extend the property based tests to use the compressions (see https://github.com/peterzeller/antidote_crdt/commit/79cbc142c8f8f6e9607058c4e7a9ad7b10482f73). 

I am not sure, if I used the function correctly, since some tests are failing. Maybe you can have a look at it? For example the MV-register test does not work (run it with `rebar3 proper -m prop_crdt_mvreg -n 10000
`).

I would expect that `compress({a, Token1, [Token0]}, {a, Token2, [Token1]})` should return `{noop, {a, Token2, [Token0, Token1]}})`, but it actually returns `{noop, {a, Token2, [Token1]}}`.

And maybe you can explain the meaning of the `compress` return value with a comment in `antidote_crdt.erl`. For example I would like to know if there is a difference between `{noop, X}` and `{X, noop}` and whether it is possible to get `{noop, noop}` or `{X,X}`.

**Comment by gmcabrita** [comment]
Looking at `compress({a, Token1, [Token0]}, {a, Token2, [Token1]})` the expected result should be `{noop, {a, Token2, [Token0]}}`. `Token1` is not needed in the list of removed tokens in the new version of the second operation since the original version of the first operation was the one that added it but in reality it will never be propagated to other replicas.

It seems that input was triggering an edge case where the input was indeed returning `{noop, {a, Token2, [Token1]}}`. The solution is simply to consider that if `A` becomes a `noop` then the tokens `B` is to remove must be updated (to include the ones that `A` was removing).

I tested the fix with your proptest and it seems to work correctly. I also ran the proptest for the other data types and two of them seem to have some issues as well:
```
===> 
11/13 properties passed, 2 failed
===> Failed test cases:
  prop_crdt_gmap:prop_gmap_spec() -> false
  prop_crdt_fat_counter:prop_fat_counter_spec() -> false
```
I'll look into these now.

> For example I would like to know if there is a difference between `{noop, X}` and `{X, noop}` and whether it is possible to get `{noop, noop}` or `{X,X}`.

To understand this we must first understand how the compression is used. The use case is that we have a list of unpropagated downstream operations, and every time we add a new operation to this list we try to compress the operation being added with the older ones (starting from the end of the list, i.e. the most recent operation).

If we run `compress(A,B)` where `A` is in index 3 in the list, and `B` is the new operation being added to the list, if it returns `{X, noop}` then `X` will replace `A` at index 3 in the list and the compression loop will stop. If it returns `{noop, X}` then `A` is removed from the list and `X` will then attempt to be compressed with the operation in index 2 in the list.

Additionally it is possible to return `{noop, noop}`, e.g. in the OR-Set: `compress([{a, [Token1], []}], [{a, [], [Token1]}]) = {noop, noop}` because the first operation would add `Token1` for `a` and the second removes `Token1` for `a`. So either applying both operations or applying none gives us the same state, so we cut both.

Returning `{X, X}` is also possible but I'm not sure if it's ever useful to do so for normal CRDTs. In the implementation of [one my non-uniform data types for my MSc thesis](https://github.com/gmcabrita/antidote_ccrdt/blob/master/src/antidote_ccrdt_topk_rmv.erl#L198-L202) it was useful to slightly change the operation to signal that we only wanted it to be propagated to a subset of replicas (we were doing this for the masked operations of non-uniform CRDTs).

I hope the explanation was not too confusing.

**Comment by gmcabrita** [comment]
Ok, the issue with the Fat Counter was that we were compressing increments. This is not safe at all, as conflating increments (which all have different tokens) means we cannot safely reset the state later.

The only safe way of doing so is to change the downstream increment to a delta-state operation (in this case an orddict containing only the new Token and Value).

**Comment by gmcabrita** [comment]
I have fixed the compression for the gmap on the latest commit.

However there is something to consider regarding the gmap property-testing, consider the following failure:
```
Shrinking ......................(22 time(s))
[{exec,dc2,{update,{{a,antidote_crdt_orset},{add,a}}}},{exec,dc2,{reset,{}}},{pull_compress,dc2,dc1}]
Checking value on dc1
Expected value: [{{a,antidote_crdt_orset},[]}]
Actual value  : []
```

The test expects the final state of the gmap to have a key `a` with an empty orset, however the execution adds some element `a` on dc2 then resets the gmap on dc2. When compressing those two orset operations inside the gmap they are treated as a no-op which is why the end result in dc1 is an empty map.

When running the proptests a few more times I see similar results for things that can generate no-ops, like counters (e.g. adding and removing to a total delta of 0) and gmaps (e.g. repeating this same thing but inside a gmap entry).

So now my question is what behavior do we want for the gmap? Do we want to enforce the creation of an empty orset with key `a` on the gmap at dc1?

**Comment by peterzeller** [comment]
> So now my question is what behavior do we want for the gmap? Do we want to enforce the creation of an empty orset with key a on the gmap at dc1?

I would say, that operation compression should not change the semantics of the data types.
For the gmap and aw-map an operation on a key means that the entry is created in the map, so this effect should be maintained after compression.

**Comment by gmcabrita** [comment]
Ok. I guess we can change the compression functions of all supported data types to never generate complete no-ops.  For example, in the counter `compress(5, -5)` the result would now be `{noop, 0}` instead of `{noop, noop}`. This way the maps should maintain their semantics.

An alternative would be to consider the `{noop, noop}` cases inside the map data types and somehow signal that the CRDT needs to be created regardless (with the default state).  This could be done by adding an extra update-effect to each data type: `update(identity, State) -> {ok, State}`. The disadvantage is that compression functions also have to be updated to consider the new update-effect.

**Comment by gmcabrita** [comment]
The property-tests are now passing.

**Comment by peterzeller** [comment]
@bieniusa: In the discussion yesterday it sounded like you did not want to include this in Antidote master, because it adds too much complexity. Did I get that correctly? 

If yes, you can close this PR. If we want to merge it, I would clarify the interface for operation compression as I suggested above.

**Comment by bieniusa** [comment]
I will close it for the moment - this requires some more thoughts.

**Pull request closed without merging**
